bpftrace: add bcc to REQUIRED_DISTRO_FEATURES
Fixes:
     ERROR: Nothing PROVIDES 'bcc' (but /buildarea/eng5/lxgit/lts24/layers/meta-clang/dynamic-layers/openembedded-layer/
     recipes-devtools/bpftrace/bpftrace_0.20.1.bb DEPENDS on or otherwise requires it). Close matches:
     bc
     byacc
     ERROR: Required build target 'meta-world-pkgdata' has no buildable providers.
     Missing or unbuildable dependency chain was: ['meta-world-pkgdata', 'bpftrace', 'bcc']

Issue: LIN1024-700

(LOCAL REV: NOT UPSTREAM) -- will send to meta-clang

Signed-off-by: Archana Polampalli <archana.polampalli@windriver.com>
Signed-off-by: Divya Chellam <divya.chellam@windriver.com>