Clang: Fix clang conflict with llvm
Issue: LIN1024-8021

Made Clang as the preferred provider for llvm to fix below error:
Error: Transaction test error: file /usr/lib/libLLVM.so.18.1 conflicts between attempted
installs of llvm-18.1.6-r0.corei7_64 and clang-libllvm-18.1.6-r0.corei7_64 on core-image-base image

(LOCAL REV: NOT UPSTREAM) -- WR Linux specific, upstream has moved clang recipe to oe-core

Signed-off-by: Hongxu Jia <hongxu.jia@windriver.com>
Signed-off-by: Sundeep KOKKONDA <sundeep.kokkonda@windriver.com>