clang/common-source.inc: fix is_work_shared_spdx leaking
The original definition of is_work_shared_spdx is in oe-core, meta-clang
redefine it in common-source.inc to fix clang spdx shared workdir failed.
But the is_work_shared_spdx in clang is leaked to other unrelated recipes
occasionally, even though other recipe do not include or require
common-source.inc

In meta-clang, function is_work_shared_spdx always return True,
define function test_clang and use it for leaking proving

    --- a/recipes-devtools/clang/common-source.inc
    +++ b/recipes-devtools/clang/common-source.inc
    @@ -15,3 +15,6 @@ do_create_spdx[depends] += "llvm-project-source-${PV}:do_patch"
     # return always true to fix that
     def is_work_shared_spdx(d):
         return True
    +
    +def test_clang():
    +    bb.warn("Fucntion in meta-clang has been leaked")

In oe-core, remove the original definition of is_work_shared_spdx in
meta/classes/create-spdx-2.2.bbclass to avoid conflict, and redefine
it in meta/classes-global/base.bbclass to always return False.

Call is_work_shared_spdx during recipe parsing. If return True and
call test_clang to prove the function is leaked from meta-clang

    --- a/meta/classes-global/base.bbclass
    +++ b/meta/classes-global/base.bbclass
    @@ -761,5 +761,13 @@ python do_cleanall() {
     }
     do_cleanall[nostamp] = "1"

    +def is_work_shared_spdx(d):
    +    return False
    +
    +python() {
    +    if is_work_shared_spdx(d):
    +        test_clang()
    +        bb.fatal(f"{d.getVar('PN')}: The func should be False, but return {is_work_shared_spdx(d)}")
    +}

    --- a/meta/classes/create-spdx-2.2.bbclass
    +++ b/meta/classes/create-spdx-2.2.bbclass
    @@ -82,9 +82,6 @@ def recipe_spdx_is_native(d, recipe):
           a.annotator == "Tool: %s - %s" % (d.getVar("SPDX_TOOL_NAME"), d.getVar("SPDX_TOOL_VERSION")) and
           a.comment == "isNative" for a in recipe.annotations)

    -def is_work_shared_spdx(d):
    -    return 'work-shared' in d.getVar('S')
    -
     def get_json_indent(d):
         if d.getVar("SPDX_PRETTY") == "1":
             return 2

Then, build from a clean project

$ rm cache/ sstate-cache tmp -rf && bitbake bash -n
...
WARNING: oe-core/meta/recipes-core/glibc/cross-localedef-native_2.39.bb: Fucntion in meta-clang has been leaked
ERROR: oe-core/meta/recipes-core/glibc/cross-localedef-native_2.39.bb: cross-localedef-native: The func should be False, but return True
...

From above log, recipe cross-localedef-native_2.39.bb did not include or
require common-source.inc, but call is_work_shared_spdx and test_clang in
clang

Remove the override is_work_shared_spdx in meta-clang, we will fix spdx
shared workdir detection for wr-sbom via other solution later

Issue: LINUXEXEC-33063
(LOCAL REV: NOT UPSTREAM) -- Will send to upstream later

Signed-off-by: Hongxu Jia <hongxu.jia@windriver.com>